### ISSUE TITLE
[Invalid Message] debug.traceTransaction returns "none too low" for querying transaction trace

### ISSUE THREAD

**Issue by anhntbk08** [BuildOnViction/victionchain#109]
Scenario: Testing **traceTransaction** thru console or rpc with no-confirmation transactions.

Currently: Message returns **nonce too low**

```
debug.traceTransaction("0x030460ca4ffa9f520a789e9e18c3ad8faefd7ff37641663e079ad5932adf36e8", { tracer: 'callTracer', timeout: '120s' })
```
Error: tracing failed: nonce too low
    at web3.js:3143:20
    at web3.js:6427:15
    at web3.js:5106:36
    at <anonymous>:1:1

**Expected**:
Message should return "Tx has not been confirmed yet !!"

**Comment by thanhson1085** [comment]
Current testnet issue:

```
$ tomo attach https://rpc.testnet.tomochain.com
Welcome to the Tomo JavaScript console!

instance: tomo/v2.1.0-beta-eb530a63/linux-amd64/go1.13.7
coinbase: 0xd76fd76f7101811726dce9e43c2617706a4c45c8
at block: 271229 (Mon, 24 Feb 2020 11:03:43 UTC)
 modules: debug:1.0 eth:1.0 miner:1.0 net:1.0 rpc:1.0 tomox:1.0 txpool:1.0 web3:1.0

> debug.traceTransaction('0xc575402f60078373cc98c97b5e31fa0f490b32f929a9775dd9cb8db1fbe0c1f8')
Error: tx 96948be0bba8191a6d3cd256f3974dd2e42c28cc04d912293995120f82fdf4fe failed: nonce too low
    at web3.js:3143:20
    at web3.js:6427:15
    at web3.js:5106:36
    at <anonymous>:1:1

> 

```
