### ISSUE TITLE
blockchain.go:460 panic: interface conversion: interface {} is nil

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/victionchain#298]
```

INFO [06-29|13:38:38] Maximum peer count                       ETH=25 LES=0 total=25
INFO [06-29|13:38:38] TomoX datadir                            path=/home/bnbprd/.tomo
INFO [06-29|13:38:38] Allocated cache and file handles         database=/home/bnbprd/.tomo cache=128 handles=1024
INFO [06-29|13:38:38] Starting peer-to-peer node               instance=tomo/binance_staking_11/v2.2.4-stable/linux-amd64/go1.12.17
INFO [06-29|13:38:38] Allocated cache and file handles         database=/server/tomo/data/folder/tomo/chaindata cache=768 handles=1024
INFO [06-29|13:38:39] Initialised chain configuration          config="{ChainID: 88 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}"
INFO [06-29|13:38:39] Initialising Ethereum protocol           versions="[63 62]" network=88
WARN [06-29|13:38:39] Head block missing, resetting chain      hash=017c49…5793f4
WARN [06-29|13:38:39] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/tomochain/tomochain/core.(*BlockChain).CurrentBlock(...)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:460
github.com/tomochain/tomochain/core.(*BlockChain).SetHead(0xc000179000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:401 +0xc71
github.com/tomochain/tomochain/core.(*BlockChain).ResetWithGenesisBlock(0xc000179000, 0xc00022fef0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:555 +0x54
github.com/tomochain/tomochain/core.(*BlockChain).Reset(0xc000179000, 0x12a325e, 0x23)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:548 +0x37
github.com/tomochain/tomochain/core.(*BlockChain).loadLastState(0xc000179000, 0x0, 0xc00022fef0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:290 +0x199c
github.com/tomochain/tomochain/core.NewBlockChain(0x1532440, 0xc00022f050, 0xc002dd89c0, 0xc000208500, 0x153a760, 0xc00020e300, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:234 +0x75c
github.com/tomochain/tomochain/core.NewBlockChainEx(0x1532440, 0xc00022f050, 0x7fd825fb39a8, 0xc0003334f0, 0xc002dd89c0, 0xc000208500, 0x153a760, 0xc00020e300, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/blockchain.go:257 +0xaf
github.com/tomochain/tomochain/eth.New(0xc0000a4a60, 0xc0004b8500, 0xc000208100, 0xc00007c880, 0x0, 0x0, 0xc000032758)
        /home/travis/gopath/src/github.com/tomochain/tomochain/eth/backend.go:185 +0x798
github.com/tomochain/tomochain/cmd/utils.RegisterEthService.func2(0xc0000a4a60, 0xc0001b0d20, 0xc0002c1110, 0xc000032758, 0x0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/cmd/utils/utils.go:27 +0xce
github.com/tomochain/tomochain/node.(*Node).Start(0xc0004b3680, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/node/node.go:182 +0x400
github.com/tomochain/tomochain/cmd/utils.StartNode(0xc0004b3680)
        /home/travis/gopath/src/github.com/tomochain/tomochain/cmd/utils/cmd.go:66 +0x2f
main.startNode(0xc00026cb00, 0xc0004b3680, 0x0, 0x58, 0x0, 0x0, 0x0, 0x64, 0x0, 0x400, ...)
        /home/travis/gopath/src/github.com/tomochain/tomochain/cmd/tomo/main.go:228 +0x89
main.tomo(0xc00026cb00, 0xe, 0x501bd00)
        /home/travis/gopath/src/github.com/tomochain/tomochain/cmd/tomo/main.go:218 +0xaa
gopkg.in/urfave/cli%2ev1.HandleAction(0x10aa740, 0x12ec1f0, 0xc00026cb00, 0xc00026cb00, 0xc0004a7f58)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00020cea0, 0xc0000b8000, 0x11, 0x12, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x590
main.main()
        /home/travis/gopath/src/github.com/tomochain/tomochai

Yijun Zhou, [29.06.20 20:40]
n/cmd/tomo/main.go:207 +0x55
```

**Comment by oggy95** [comment]
Same issue
tomo version v2.3.0
