### ISSUE TITLE
panic when sync

### ISSUE THREAD

**Issue by whs1995** [BuildOnViction/victionchain#311]
**when I try to sync,I get the following errors**

```
nohup tomo --syncmode "fast" --datadir /data/tomo_data/data --port 30303 --rpc --rpcaddr 0.0.0.0 --rpcport 8575 --rpcapi "admin,db,eth,net,web3,personal" >/data/tomo_data/data/tomo.log 2>&1 &
```
**wait a few minute**

```
WARN [08-24|15:00:18] Synchronisation failed, dropping peer    peer=3866519c6719213a err="no peers available or all tried for download"
INFO [08-24|15:02:20] Imported new block headers               count=0   elapsed=77.910ms number=224 hash=720a86…8898f3 ignored=192
INFO [08-24|15:02:21] Imported new block receipts              count=0   elapsed=30.923μs number=34  hash=428031…08470b size=0.00B ignored=2
INFO [08-24|15:02:21] Imported new block headers               count=0   elapsed=74.815ms number=416 hash=0b1a1e…370e94 ignored=192
INFO [08-24|15:02:22] Imported new block headers               count=0   elapsed=74.156ms number=608 hash=e3cbb6…9749a0 ignored=192
INFO [08-24|15:02:22] Imported new block receipts              count=2   elapsed=435.96μs number=36  hash=afe7fc…26ba92 size=9.08kB ignored=0
INFO [08-24|15:02:24] Imported new block receipts              count=2   elapsed=425.064μs number=38  hash=fa44cf…f0184f size=6.82kB ignored=0
INFO [08-24|15:02:24] Imported new block headers               count=32  elapsed=75.012ms  number=800 hash=91878e…c04bc5 ignored=160
INFO [08-24|15:02:27] Imported new block receipts              count=2   elapsed=445.515μs number=40  hash=752c24…7de640 size=7.57kB ignored=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e627a]

goroutine 85563 [running]:
github.com/tomochain/tomochain/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/types/block.go:420 +0x4a
github.com/tomochain/tomochain/core/state.GetSigners(0xc00e23b770, 0x0, 0x9c3d7f7dfc3ae1bb, 0xf4f2899df35e8b86, 0x24862920970e39e9)
        /home/travis/gopath/src/github.com/tomochain/tomochain/core/state/statedb_utils.go:22 +0x81
github.com/tomochain/tomochain/contracts.GetSignersFromContract(...)
        /home/travis/gopath/src/github.com/tomochain/tomochain/contracts/utils.go:212
```

**Comment by whs1995** [comment]
V2.2.4

**Comment by thanhson1085** [comment]
required synmode = "full"

**Comment by whs1995** [comment]
> required synmode = "full"
Problem solved. Thanks for your help!
