### ISSUE TITLE
tomo stop sync with followed error

### ISSUE THREAD

**Issue by lcgogo** [BuildOnViction/victionchain#327]
docker logs --tail 200 tomo-2.3.0
Using account a9bede5c03f61f483182ddbcbcd95cd3a9111481
WS_SECRET not set, will not report to netstats server.
+ exec tomo --networkid 88 --unlock a9bede5c03f61f483182ddbcbcd95cd3a9111481 --syncmode full --verbosity 3 --datadir data --keystore keystore --identity unnamed_JheKGw --maxpeers 25 --password ./password --port 30303 --txpool.globalqueue 5000 --txpool.globalslots 5000 --rpc --rpccorsdomain '*' --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts '*' --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins '*' --mine --gasprice 250000000 --targetgaslimit 84000000 tomo --networkid 88 --unlock a9bede5c03f61f483182ddbcbcd95cd3a9111481 --syncmode full --verbosity 3 --datadir data --keystore keystore --identity unnamed_EUBKuV --maxpeers 25 --password ./password --port 30303 --txpool.globalqueue 5000 --txpool.globalslots 5000 --rpc --rpccorsdomain snap --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts snap --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins snap --mine --gasprice 250000000 --targetgaslimit 84000000 --rollback
dump: unnamed_JheKGw a9bede5c03f61f483182ddbcbcd95cd3a9111481
INFO [02-27|03:40:15] Maximum peer count                       ETH=25 LES=0 total=25
INFO [02-27|03:40:15] TomoX datadir                            path=data/tomox
INFO [02-27|03:40:15] Allocated cache and file handles         database=data/tomox cache=134.22mB handles=1024
INFO [02-27|03:40:15] Starting peer-to-peer node               instance=tomo/unnamed_JheKGw/v2.3.0-stable/linux-amd64/go1.12.17
INFO [02-27|03:40:15] Allocated cache and file handles         database=/tomochain/data/tomo/chaindata cache=805.31mB handles=1024
INFO [02-27|03:40:17] Initialised chain configuration          config="{ChainID: 88 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}"
INFO [02-27|03:40:17] Initialising Ethereum protocol           versions="[63 62]" network=88
WARN [02-27|03:40:17] Head block missing, resetting chain      hash=07de9a…707377
WARN [02-27|03:40:17] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/tomochain/tomochain/core.(*BlockChain).CurrentBlock(...)
	/tomochain/core/blockchain.go:460
github.com/tomochain/tomochain/core.(*BlockChain).SetHead(0xc0024b2000, 0x0, 0x0, 0x0)
	/tomochain/core/blockchain.go:401 +0xc71
github.com/tomochain/tomochain/core.(*BlockChain).ResetWithGenesisBlock(0xc0024b2000, 0xc00074c360, 0x0, 0x0)
	/tomochain/core/blockchain.go:555 +0x54
github.com/tomochain/tomochain/core.(*BlockChain).Reset(0xc0024b2000, 0x130875f, 0x23)
	/tomochain/core/blockchain.go:548 +0x37
github.com/tomochain/tomochain/core.(*BlockChain).loadLastState(0xc0024b2000, 0x0, 0xc00074c360)
	/tomochain/core/blockchain.go:290 +0x1a03
github.com/tomochain/tomochain/core.NewBlockChain(0x16e0c60, 0xc001b8bc60, 0xc00244f4e0, 0xc0000f2800, 0x16da460, 0xc001c9c240, 0x0, 0x0, 0x0, 0x0, ...)
	/tomochain/core/blockchain.go:234 +0x775
github.com/tomochain/tomochain/core.NewBlockChainEx(0x16e0c60, 0xc001b8bc60, 0x7f1a5f9dbe70, 0xc00013c660, 0xc00244f4e0, 0xc0000f2800, 0x16da460, 0xc001c9c240, 0x0, 0x0, ...)
	/tomochain/core/blockchain.go:257 +0xbc
github.com/tomochain/tomochain/eth.New(0xc0005f44a0, 0xc00072c500, 0xc0000f2180, 0xc0000c6740, 0x0, 0x0, 0xc000034ab8)
	/tomochain/eth/backend.go:182 +0x777
github.com/tomochain/tomochain/cmd/utils.RegisterEthService.func2(0xc0005f44a0, 0xc000606600, 0xc0001e1110, 0xc000034ab8, 0x0)
	/tomochain/cmd/utils/utils.go:27 +0xce
github.com/tomochain/tomochain/node.(*Node).Start(0xc00072ea00, 0x0, 0x0)
	/tomochain/node/node.go:183 +0x400
github.com/tomochain/tomochain/cmd/utils.StartNode(0xc00072ea00)
	/tomochain/cmd/utils/cmd.go:66 +0x2f
main.startNode(0xc0000e49a0, 0xc00072ea00, 0x0, 0x58, 0x0, 0x0, 0x0, 0x64, 0x0, 0x400, ...)
	/tomochain/cmd/tomo/main.go:228 +0x89
main.tomo(0xc0000e49a0, 0x0, 0x0)
	/tomochain/cmd/tomo/main.go:218 +0xaa
gopkg.in/urfave/cli%2ev1.HandleAction(0x11075a0, 0x1474920, 0xc0000e49a0, 0x0, 0xc000717f58)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000192340, 0xc000032600, 0x5d, 0x60, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x590
main.main()
	/tomochain/cmd/tomo/main.go:207 +0x55

**Comment by lcgogo** [comment]
same issue again
```shell
Using account b45c5dc5dcf9b12525ddb5149af10d893f7142ca
WS_SECRET not set, will not report to netstats server.
dump: unnamed_5dQdRl b45c5dc5dcf9b12525ddb5149af10d893f7142ca
+ exec tomo --networkid 88 --unlock b45c5dc5dcf9b12525ddb5149af10d893f7142ca --syncmode full --verbosity 3 --datadir data --keystore keystore --identity unnamed_5dQdRl --maxpeers 25 --password ./password --port 30303 --txpool.globalqueue 5000 --txpool.globalslots 5000 --rpc --rpccorsdomain '*' --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts '*' --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins '*' --mine --gasprice 250000000 --targetgaslimit 84000000
INFO [03-21|04:28:24] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-21|04:28:24] TomoX datadir                            path=data/tomox
INFO [03-21|04:28:24] Allocated cache and file handles         database=data/tomox cache=134.22mB handles=1024
INFO [03-21|04:28:24] Starting peer-to-peer node               instance=tomo/unnamed_5dQdRl/v2.3.1-stable/linux-amd64/go1.12.17
INFO [03-21|04:28:24] Allocated cache and file handles         database=/tomochain/data/tomo/chaindata cache=805.31mB handles=1024
INFO [03-21|04:28:27] Initialised chain configuration          config="{ChainID: 88 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: posv}"
INFO [03-21|04:28:27] Initialising Ethereum protocol           versions="[63 62]" network=88
WARN [03-21|04:28:27] Head block missing, resetting chain      hash=8a1e75…fe0c58
WARN [03-21|04:28:27] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/tomochain/tomochain/core.(*BlockChain).CurrentBlock(...)
	/tomochain/core/blockchain.go:460
github.com/tomochain/tomochain/core.(*BlockChain).SetHead(0xc00bdba000, 0x0, 0x0, 0x0)
	/tomochain/core/blockchain.go:401 +0xc71
github.com/tomochain/tomochain/core.(*BlockChain).ResetWithGenesisBlock(0xc00bdba000, 0xc000238ab0, 0x0, 0x0)
	/tomochain/core/blockchain.go:555 +0x54
github.com/tomochain/tomochain/core.(*BlockChain).Reset(0xc00bdba000, 0x130875f, 0x23)
	/tomochain/core/blockchain.go:548 +0x37
github.com/tomochain/tomochain/core.(*BlockChain).loadLastState(0xc00bdba000, 0x0, 0xc000238ab0)
	/tomochain/core/blockchain.go:290 +0x1a03
github.com/tomochain/tomochain/core.NewBlockChain(0x16e0b20, 0xc00a119b80, 0xc00bc35320, 0xc0000f0c00, 0x16da280, 0xc00a124300, 0x0, 0x0, 0x0, 0x0, ...)
	/tomochain/core/blockchain.go:234 +0x775
github.com/tomochain/tomochain/core.NewBlockChainEx(0x16e0b20, 0xc00a119b80, 0x7f4cbb09eae0, 0xc00013ad20, 0xc00bc35320, 0xc0000f0c00, 0x16da280, 0xc00a124300, 0x0, 0x0, ...)
	/tomochain/core/blockchain.go:257 +0xbc
github.com/tomochain/tomochain/eth.New(0xc00051e3c0, 0xc000518000, 0xc0000f0880, 0xc000517f00, 0x0, 0x0, 0xc0000353b8)
	/tomochain/eth/backend.go:182 +0x777
github.com/tomochain/tomochain/cmd/utils.RegisterEthService.func2(0xc00051e3c0, 0xc0005ca300, 0xc000331110, 0xc0000353b8, 0x0)
	/tomochain/cmd/utils/utils.go:27 +0xce
github.com/tomochain/tomochain/node.(*Node).Start(0xc0002fea00, 0x0, 0x0)
	/tomochain/node/node.go:183 +0x400
github.com/tomochain/tomochain/cmd/utils.StartNode(0xc0002fea00)
	/tomochain/cmd/utils/cmd.go:66 +0x2f
main.startNode(0xc0000e49a0, 0xc0002fea00, 0x0, 0x58, 0x0, 0x0, 0x0, 0x64, 0x0, 0x400, ...)
	/tomochain/cmd/tomo/main.go:228 +0x89
main.tomo(0xc0000e49a0, 0xe, 0x501bd00)
	/tomochain/cmd/tomo/main.go:218 +0xaa
gopkg.in/urfave/cli%2ev1.HandleAction(0x11075a0, 0x1474920, 0xc0000e49a0, 0xc0000e49a0, 0xc000577f58)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000ae4e0, 0xc000032300, 0x2e, 0x30, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x590
main.main()
	/tomochain/cmd/tomo/main.go:207 +0x55
```

**Comment by thanhnguyennguyen** [comment]
please use v2.3.1 and latest snapshot here
https://tomotools.com/
