### ISSUE TITLE
BUG! PLEASE REPORT 

### ISSUE THREAD

**Issue by zhy827827** [BuildOnViction/victionchain#382]
```
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/tomochain/tomochain/issues
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: index allocation went beyond available resultCache space
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/queue.go:510
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: goroutine 31084 [running]:
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: runtime/debug.Stack(0x53, 0x0, 0x0)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/.gimme/versions/go1.12.17.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: runtime/debug.PrintStack()
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/.gimme/versions/go1.12.17.linux.amd64/src/runtime/debug/stack.go:16 +0x22
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/common.Report(0xc01bc33a70, 0x1, 0x1)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/common/debug.go:35 +0x1a5
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*queue).reserveHeaders(0xc01af14300, 0xc00f253ef0, 0x80, 0xc01e41bbc0, 0xc000010590, 0xc01e41bbf0, 0xc01e41bc20, 0x146c328, 0x146d948, 0x146d938, ...)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/queue.go:510 +0x6c1
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*queue).ReserveBodies(0xc01af14300, 0xc00f253ef0, 0x80, 0x0, 0xc00f253e00, 0x0, 0x0)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/queue.go:462 +0xe4
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*Downloader).fetchParts(0xc0004ed800, 0x169eb80, 0xc000525490, 0xc01af128a0, 0xc01b034210, 0xc00056a5b0, 0xc01bc33eb0, 0xc01bc33f00, 0xc01bc33ef0, 0xc01bc33ee0, ...)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/downloader.go:1116 +0x8dd
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*Downloader).fetchBodies(0xc0004ed800, 0x4127e1c, 0x53d28448c2198045, 0xc03f93bf98)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/downloader.go:937 +0x311
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*Downloader).syncWithPeer.func4(0x49ed91d800000008, 0x146d958)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/downloader.go:466 +0x36
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: github.com/tomochain/tomochain/eth/downloader.(*Downloader).spawnSync.func1(0xc01cadcbd0, 0xc003d77f80, 0xc03f4f7b80)
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/downloader.go:486 +0x51
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: created by github.com/tomochain/tomochain/eth/downloader.(*Downloader).spawnSync
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]:         /home/travis/gopath/src/github.com/tomochain/tomochain/eth/downloader/downloader.go:486 +0xc3
Sep 25 03:01:39 rockx-mainnet-access-tomochain-01 sh[535581]: #### BUG! PLEASE REPORT ####

```

**Comment by fatihohn** [comment]
I've encountered the same log after having some hard time syncing due to repetitive rpc timeout error like below
`[ERROR] ... RPC execBacth write tcp 10.0.1.5:3000->10.0.1.12:55030: i/o timeout ...`

**Comment by tungng98** [comment]
> I've encountered the same log after having some hard time syncing due to repetitive rpc timeout error like below `[ERROR] ... RPC execBacth write tcp 10.0.1.5:3000->10.0.1.12:55030: i/o timeout ...`

As my observation, this issue usually happens when node cannot handle all the incoming RPC requests.
